[package]
name = "glues"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Lightweight TUI note-taking app with Git, CSV, and JSON support - privacy-focused and sync-enabled"
readme = "../README.md"
keywords = ["tui", "note-taking", "notes-app", "cursive", "data-privacy"]

[dependencies]
glues-core.workspace = true
gluesql.workspace = true
cursive = "0.21.1"
futures = "0.3.30"
async-io = "2.3.2"
