[package]
name = "glues"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
description = "TUI-based note-taking application supporting multiple formats (git, CSV, JSON) for data storage"

[dependencies]
glues-core.workspace = true
gluesql.workspace = true
cursive = "0.21.1"
futures = "0.3.30"
async-io = "2.3.2"
