[workspace]
resolver = "2"
members = ["tui", "ratatui", "core"]
default-members = ["tui", "ratatui", "core"]

[workspace.package]
authors = ["Taehoon Moon <taehoon.moon@outlook.com>"]
version = "0.2.2"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/gluesql/glues"

[workspace.dependencies]
glues-core = { path = "./core", version = "0.2.2" }

[workspace.dependencies.gluesql]
version = "0.16.1"
default-features = false
features = [
    "gluesql_memory_storage",
    "gluesql-csv-storage",
    "gluesql-json-storage",
    "gluesql-file-storage",
    "gluesql-git-storage",
]
