[package]
name = "glues-core"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gluesql.workspace = true
thiserror = "1.0.61"
async-recursion = "1.1"
uuid = { version = "1.8.0", features = ["v7"] }
