[package]
name = "glues-core"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Headless state management module for Glues Notes"

[dependencies]
gluesql.workspace = true
thiserror = "1.0.61"
async-trait = "0.1"
async-recursion = "1.1"
uuid = { version = "1.10", features = ["v7"] }
